const toRecord = [
    'My voice is my passport verify me.',
    'I am going to make him an offer he cannot refuse.',
    'My name is unknown to you.',
    'My voice is my passport verify me.',
    'I am going to make him an offer he cannot refuse.',
    'My name is unknown to you.',
    'My voice is my passport verify me.',
    'I am going to make him an offer he cannot refuse.',
    'My name is unknown to you.',
    'My voice is my passport verify me.',
    'I am going to make him an offer he cannot refuse.',
    'My name is unknown to you.',
    'My voice is my passport verify me.',
    'I am going to make him an offer he cannot refuse.',
    'My name is unknown to you.',
    'He faced Russian wrestler Serg White.',
    'The viaduct terminates at the Battery Street Tunnel.',
    'This process is known as selective breeding.',
    'Returning she would find his name, and smile.',
    'These supporters always bring flares, drums and large national flags to the stadiums.',
    'His great play earned him First-Team All-Big Ten Conference honors as a junior.',
    'It is the site of an Aurora Cooperative grain elevator facility.',
    'His son, the Reverend Watson Franks, preached the funeral.',
    'In reality, there is no target.',
    'He was capped three times by Australia.',
    'Brackish marshes have formed where channels and streams enter the lake.',
    'His identity remains an open question.',
    'The recording was done by Pittsburgh musician and recording engineer, Jonathan Gunnell.',
    'Bonus Eventus had a temple of unknown date in the Campus Martius.',
    'This was changed after several revisions of the agreement.',
    'The Capitol Reef National Park Visitors Center is to the east.',
    'Bock was named by railroad officials.',
    'Behind the viewer is Upright Gate, the principal entrance to the imperial palace grounds.',
    'Lincolns intervention was not popular at the time.',
    'His specialty was writing about what was at the time recent and popular history.',
    'In December, she got underway to conduct standardization trials, followed by shakedown training.',
    'Tales depict the Dagda as a figure of immense power.',
    'Adjacent to Poldasht city is the Aras River Dam and an Iranian border terminal.',
    'It is open without charge during daylight hours.',
    'That is a flagrant assault on free speech.',
    'This implies a difference between common people and the elite.',
    'Consequently, an individuals understanding of the past is strongly linked to this group consciousness.',
    'Legal scholars disagree on the legitimacy of her claim.',
    'The bark of the pine tree was shiny and dark.',
    'Leaves turn brown and yellow in the fall.',
    'The pennant waved when the wind blew.',
    'Split the log with a quick, sharp blow.',
    'Burn peat after the logs give out.',
    'He ordered peach pie with ice cream.',
    'Weave the carpet on the right hand side.',
    'Hemp is a weed found in parts of the tropics.',
    'A lame back kept his score low.',
    'We find joy in the simplest things.',
    'The name was later shortened to Star Valley.',
    'Written in Latin, they were modelled on Horace and Martial.',
    'Anna then enrolled James in the Imperial Academy of Arts at Saint Petersburg.',
    'He grew up in the town of Newbridge, Caerphilly.',
    'Inland areas of the park also provide bear viewing.',
    'This includes taking a flying test.',
    'He said, there must be some difference stylistically between Clark and Superman.',
    'These supporters always bring flares, drums and large national flags to the stadiums.',
    'It is the site of an Aurora Cooperative grain elevator facility.',
    'Nudge gently but wake her now.',
    'The news struck doubt into restless minds.',
    'Once we stood beside the shore.',
    'A chink in the wall allowed a draft to blow.',
    'Fasten two pins on each side.',
    'A cold dip restores health and zest.',
    'He takes the oath of office each March.',
    'The sand drifts over the sill of the old house.',
    'The point of the steel pen was bent and twisted.',
    'There is a lag between thought and act.',
    'Vatican City and San Marino also use the Italian postal code system.',
    'The team played its home games at Marquette Stadium.',
    'The dock also handled agricultural produce from Ireland and the Mediterranean.',
    'Jaynes strongly promoted the interpretation of probability theory as an extension of logic.',
    'The City of Saint Croix Falls is located within the town.',
    'Riders in italics are active.',
    'Sexual contact and vertical transmission may occur.',
    'In three weeks, we became number one.',
    'She is best known for being the first female recipient of the Navy Cross.',
    'The Capitol Reef National Park Visitors Center is to the east.',
    'She was eventually put on a list for donation for museum status.',
    'He also returned to writing chamber music and symphonic works.',
    'Three hours after arriving in Johannesburg, South African Police stormed the aircraft.'
];

export {toRecord};